AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "lib/rubowar/arena.rb"
    - "lib/rubowar/renderers/**/*"
    - "rubots/**/*"

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "lib/rubowar/arena.rb"
    - "robots/**/*"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/rubowar/arena.rb"
    - "lib/rubowar/battle.rb"
    - "robots/**/*"

Metrics/PerceivedComplexity:
  Exclude:
    - "lib/rubowar/arena.rb"
    - "lib/rubowar/battle.rb"
    - "robots/**/*"

Metrics/ClassLength:
  Max: 200
  Exclude:
    - "lib/rubowar/arena.rb"
    - "robots/**/*"

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  CountKeywordArgs: false

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "bin/simulate"
